global:
  scrape_interval: 10s
scrape_configs:

  - job_name: 'laa-ccms-caab'
    metrics_path: '/civil/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8010' ]

  - job_name: 'laa-ccms-caab-assessment-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8008' ]

  - job_name: 'laa-ccms-caab-ebs-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8009' ]

  - job_name: 'laa-ccms-caab-soa-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8007' ]

  - job_name: 'laa-ccms-caab-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8005' ]