# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  caab-api-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-ccms-caab-api
    username: PhilDigitalJustice
    password: ${{ secrets.REPO_TOKEN }}
  assessment-api-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-ccms-caab-assessment-api
    username: PhilDigitalJustice
    password: ${{ secrets.REPO_TOKEN }}
  ebs-api-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-ccms-data-api
    username: PhilDigitalJustice
    password: ${{ secrets.REPO_TOKEN }}
  soa-api-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-ccms-soa-gateway-api
    username: PhilDigitalJustice
    password: ${{ secrets.REPO_TOKEN }}
  spring-boot-common-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-ccms-spring-boot-common
    username: PhilDigitalJustice
    password: ${{ secrets.REPO_TOKEN }}
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      gradle-updates:
        patterns:
          - "**" # Matches all Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - caab-api-github-packages
      - assessment-api-github-packages
      - ebs-api-github-packages
      - soa-api-github-packages
      - spring-boot-common-github-packages
    schedule:
      interval: "weekly"
    groups:
      internal-packages:
        patterns:
          - "**"
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
    groups:
      npm-updates:
        patterns:
          - "**" # Matches all NPM packages