# This compose file starts weblogic servers instead of Tomcat,
# to match the 6dg production environments.
#
# Usage:
#     docker-compose -f docker-compose-weblogic.yml -p weblogic up
version: "3.2"

services:
  laa-ccms-caab-saml-mock:
    container_name: laa-ccms-caab-saml-mock
    build:
      context: ../laa-ccms-caab-saml-mock
      dockerfile: ./Dockerfile-local
    ports:
      - 8081:8080

  laa-ccms-caab-db:
    container_name: laa-ccms-caab-db
    image: 902837325998.dkr.ecr.eu-west-2.amazonaws.com/laa-ccms-pui-oracle-database:latest
    ports:
      - "1521:1521"
    environment:
      - DB_SID=CCMSPUI
      - DB_PASSWD=Password123!
    volumes:
      - laa-ccms-caab-data:/ORCL

  laa-ccms-caab-liquibase:
    container_name: laa-ccms-caab-liquibase
    build:
      context: https://github.com/ministryofjustice/docker-liquibase.git
    volumes:
      - ../laa-ccms-caab-db/sql:/migrations
      - ../laa-ccms-caab-db/waitfor:/waitfor
    depends_on:
      - laa-ccms-caab-db
    entrypoint: /bin/bash
    command: [ "./waitfor/wait_for.sh" ]

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8051:8080"
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  laa-ccms-caab-data:
  clam:
  wiremock:
