services:
  laa-ccms-caab-saml-mock:
    container_name: laa-ccms-caab-saml-mock
    build:
      context: ../laa-ccms-caab-saml-mock
    ports:
      - "8081:8080"

  laa-ccms-mock-contracts:
    container_name: laa-ccms-caab-mock-contracts
    build:
      context: ../laa-ccms-mock-contracts
    ports:
      - "7777:7777"

  laa-ccms-caab-wiremock:
    container_name: laa-ccms-caab-wiremock
    image: wiremock/wiremock:3.13.2
    command: --global-response-templating
    ports:
      - "8020:8080"
    volumes:
      - ./wiremock:/home/wiremock

  laa-ccms-caab-clam-av:
    container_name: laa-ccms-caab-clam-av
    image: clamav/clamav-debian:1.5.2
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    ports:
      - "3310:3310"

  laa-ccms-caab-localstack:
    container_name: laa-ccms-caab-localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"                   # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"         # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1                                 # Logging
      - USE_SSL=1                               # Return URLs using HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"

  laa-ccms-caab-prometheus:
    container_name: laa-ccms-caab-prometheus
    image: prom/prometheus:v3
    restart: unless-stopped
    networks:
      - local-prom
    ports:
      - "9090:9090"
    volumes:
      - ./localmetrics/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  clam:
  wiremock:
  prometheus:
  grafana-storage:

networks:
  local-prom:
    driver: bridge
