# This compose file starts weblogic servers instead of Tomcat,
# to match the 6dg production environments.
#
# Usage:
#     docker-compose -f docker-compose-weblogic.yml -p weblogic up
services:
  laa-ccms-caab-saml-mock:
    container_name: laa-ccms-caab-saml-mock
    build:
      context: ../laa-ccms-caab-saml-mock
    ports:
      - 8081:8080

  #laa-ccms-caab-db:
  #  container_name: laa-ccms-caab-db
  #  image: 902837325998.dkr.ecr.eu-west-2.amazonaws.com/laa-ccms-pui-oracle-database:latest
  #  ports:
  #    - "1521:1521"
  #  environment:
  #    - DB_SID=CCMSPUI
  #    - DB_PASSWD=Password123!
  #  volumes:
  #    - laa-ccms-caab-data:/ORCL

  #laa-ccms-caab-liquibase:
  #  container_name: laa-ccms-caab-liquibase
  #  image: caab-liquibase
  #  volumes:
  #    - ../laa-ccms-caab-db/sql:/migrations
  #    - ../laa-ccms-caab-db/waitfor:/waitfor
  #  depends_on:
  #    - laa-ccms-caab-db
  #  entrypoint: /bin/bash
  #  command: [ "./waitfor/wait_for.sh" ]

  laa-ccms-caab-wiremock:
    container_name: laa-ccms-caab-wiremock
    image: wiremock/wiremock:2.35.0
    command: --global-response-templating
    ports:
      - "8051:8080"
    volumes:
      - ./wiremock:/home/wiremock

  laa-ccms-caab-clam-av:
    container_name: laa-ccms-caab-clam-av
    image: mkodockx/docker-clamav:alpine
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    ports:
      - 3310:3310

  laa-ccms-caab-localstack:
    container_name: laa-ccms-caab-localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"                   # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"         # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1                                 # Logging
      - USE_SSL=1                               # Return URLs using HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"

  laa-ccms-caab-prometheus:
    container_name: laa-ccms-caab-prometheus
    image: bitnami/prometheus
    restart: unless-stopped
    networks:
      - local-prom
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  laa-ccms-caab-data:
  clam:
  wiremock:
  prometheus:

networks:
  local-prom:
    driver: bridge