global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: 'laa-ccms-caab'
    metrics_path: '/civil/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:8010' ]

  - job_name: 'laa-ccms-caab-ebs-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:8009' ]

  - job_name: 'laa-ccms-caab-soa-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:8007' ]

  - job_name: 'laa-ccms-caab-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval:
    static_configs:
      - targets: [ 'localhost:8005' ]