search:
  max-results:
    page: 20
#    notification-count: 500
#    notifications: 500
    clients: 200
    cases: 300
#    statement-of-accounts: 400
#    organisations: 500

spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: ${SAML_METADATA_URI}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

laa:
  ccms:
    data-api:
      hostname: localhost
      port: 8009
      url: http://${laa.ccms.data-api.hostname}:${laa.ccms.data-api.port}
    soa-gateway-api:
      hostname: laa-ccms-civil-soa-gateway-api-dev
      port: 8007
      url: http://${laa.ccms.soa-gateway-api.hostname}:${laa.ccms.soa-gateway-api.port}

server:
  port: 8080
