spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: ${SAML_METADATA_URI}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}