search:
  max-results:
    page: 20
#    notification-count: 500
#    notifications: 500
    clients: 200
    cases: 100
#    statement-of-accounts: 400
    organisations: 500

upload:
  valid-extensions: >
    pdf,
    rtf,
    tiff,
    docx

submission:
  max-poll-count: 6

spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: ${SAML_METADATA_URI}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

laa:
  ccms:
    ebs-api:
      hostname: ${CAAB_EBS_API_HOSTNAME}
      url: ${laa.ccms.ebs-api.hostname}
    soa-api:
      hostname: ${CAAB_SOA_API_HOSTNAME}
      url: ${laa.ccms.soa-api.hostname}
    caab-api:
        hostname: ${CAAB_API_HOSTNAME}
        url: ${laa.ccms.caab-api.hostname}
    assessment-api:
        hostname: ${ASSESSMENT_API_HOSTNAME}
        url: ${laa.ccms.assessment-api.hostname}

os:
  api:
    url: ${OS_API_HOSTNAME}
    key: ${OS_API_KEY}

av:
  enabled: ${AV_API_ENABLED}
  api:
    hostname: ${AV_API_HOSTNAME}
    port: ${AV_API_PORT}
    timeout: ${AV_API_TIMEOUT}
