search:
  max-results:
    page: 20
#    notification-count: 500
#    notifications: 500
    clients: 200
    cases: 300
#    statement-of-accounts: 400
#    organisations: 500

spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: ${SAML_METADATA_URI}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

laa:
  ccms:
    data-api:
      hostname: laa-ccms-caab-ebs-api.live.cloud-platform.service.justice.gov.uk
      url: https://${laa.ccms.data-api.hostname}
    soa-gateway-api:
      hostname: laa-ccms-caab-soa-api.live.cloud-platform.service.justice.gov.uk
      url: http://${laa.ccms.soa-gateway-api.hostname}

server:
  port: 8080

