search:
  max-results:
    page: 20
#    notification-count: 500
#    notifications: 500
    clients: 200
    cases: 100
#    statement-of-accounts: 400
    organisations: 500

submission:
  max-poll-count: 6

portal:
  logoutUrl: ${PORTAL_URL}/oam/server/logout?end_url=${PORTAL_URL}/LAALogin/pages/Logout.jsp

spring:
  application:
    name: laa-ccms-caab
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            entity-id: caab-provider-ui
            assertingparty:
              metadata-uri: ${PORTAL_URL}/oamfed/idp/metadata
              singlesignon:
                url: ${PORTAL_URL}/oamfed/idp/initiatesso?providerid=${spring.security.saml2.relyingparty.registration.idp.entity-id}
            signing:
              credentials:
                private-key-location: ${SAML_PRIVATE_KEY}
                certificate-location: ${SAML_CERTIFICATE}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
      resolve-lazily: true
  cloud:
    aws:
      s3:
        region: ${S3_REGION}

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    session:
      timeout: 60m
    # required to be on civil in order for OPA integration with OWD,
    # otherwise issues occur with the JSESSIONID cookie
    context-path: /civil

laa:
  ccms:
    pui-home-url: ${PUI_HOME_URL}
    features:
      - feature: amendments
        enabled: ${AMENDMENTS_FEATURE_ENABLED}
    footer:
      research-panel-link: ${RESEARCH_PANEL_LINK}
    s3:
      buckets:
        document-bucket:
          name: ${S3_DOCUMENT_BUCKET}
          url-duration: 20 # (minutes) - How long generated URLs remain accessible.
    ebs-api:
      hostname: ${CAAB_EBS_API_HOSTNAME}
      url: ${laa.ccms.ebs-api.hostname}
      accessToken: ${CAAB_EBS_API_ACCESS_TOKEN}
    soa-api:
      hostname: ${CAAB_SOA_API_HOSTNAME}
      url: ${laa.ccms.soa-api.hostname}
      accessToken: ${CAAB_SOA_API_ACCESS_TOKEN}
    caab-api:
      hostname: ${CAAB_API_HOSTNAME}
      url: ${laa.ccms.caab-api.hostname}
      accessToken: ${CAAB_API_ACCESS_TOKEN}
    assessment-api:
      hostname: ${ASSESSMENT_API_HOSTNAME}
      url: ${laa.ccms.assessment-api.hostname}
      accessToken: ${ASSESSMENT_API_ACCESS_TOKEN}
    oracle-web-determination-server:
      hostname: ${OWD_URL}
      url: ${laa.ccms.oracle-web-determination-server.hostname}
      resources:
        interview-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.css
        font-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/fonts/fonts.css
        interview-javascript: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.js
      redirect:
        hostname: ${OWD_REDIRECT_URL}
        url: ${laa.ccms.oracle-web-determination-server.redirect.hostname}
    caab:
      upload:
        valid-extensions: >
          PDF,
          DOCX,
          RTF,
          TIFF
      claim-upload:
        valid-extensions: >
          XML
      opa:
        security:
          password:  ${OPA_SECURITY_PASSWORD}

os:
  api:
    url: ${OS_API_HOSTNAME}
    key: ${OS_API_KEY}

av:
  enabled: ${AV_API_ENABLED}
  api:
    hostname: ${AV_API_HOSTNAME}
    port: ${AV_API_PORT}
    timeout: ${AV_API_TIMEOUT}
