search:
  max-results:
    page: 20
    #    notification-count: 500
    #    notifications: 500
    clients: 200
    cases: 100
#    statement-of-accounts: 400
#    organisations: 500

spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: http://localhost:8081/metadata
            signing:
              credentials:
                private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDlVvOKwRqsJenZzVcz0lrGkedu+t9cTGov9kfR00lp5FOfSu8NidwTdCuPliJ+maaZ4cXUsXqQY1RxR80wtszTMla8GMkftp8cYbs5piUfH2koJ9lD+pKH4WrQtj3stBO0e4frV5/g1ymDWTNVK/0UCnsPzycUjq9+GURX6uOoJ/gi2ZzB0WQa9bKClkoTi2XuWGhOMQnZ/Kdte4OYbOk7kQ0s4H1Yz7GtWIkfmNBF9si3NcpUTY39afNcVu+ClsjrO0ogEJSSIPnY4eBEcC82QX5xYICG35Yh4IpJWLNtuaQOxtxNh68tN01pI6x0HIYjW7uHmXQ+NXzQugv4USerAgMBAAECggEBALpE5ifDcZNyc74n7nSznHD9XjigYDwKAJEV+f0tG8p63YRai1C2sN3IE/1aVof26f7ABjsbL04IrzQWukyfnDrI/vNlOi2c2RxnMHbBQBNIItOvkeKJqOveJTCBZEhVdk+3qYx3Le6jMx9wmqXJxZK6dHtBqB8lSNolUYIK0H7o9hbY7u4CwVSw4AMDY5q5djSf07CKDhOgLL3nkKONg0HYksUoaYtPahCVD75buZP+yfuLi8xhho4R8V4RMLivc+HaaQ7XGkUUEb+S7eLla+ohXze9iM1mltjQtasz4vRnsa182xO/3XPIaWROYHbhp/fCq3es1xOhmWku1TW5d1kCgYEA9eHhb2/3gilMkszjxKne0zCY+2z2Ou4ATeqZnKg5vaeWl5f86Bn5Tz2HNdkQysUNs1s3IT8eEiNeQRPMlNnP1kBQBaaqW9wmhWErWvZ+T+jNAd8cGK94EY5PnkZOpBg5S1z4XqB6s9BSM9CLwjyMwTMPwWS/S1EDYJw/c9PMcO8CgYEA7sbPc7hZyYPNmsrslQh/7EmDiXwB4FkMKAqS16m8jA2Ui4OH7T1e6sEycyGKOD6BVcF3R17PqBmpgp9AW4t4+tjUBicXHuNlkihnDrXJv5AHwPrW4NxikVue0ZvP8nKA92sonJj5/RJoTzZ0KHbGoEn5ibWyRZaeSvVTS3Q2PQUCgYAoCwY8sL5dOz6WNbnuQD/ioup3H9Kl3Da+ebNUmOz2XwGeZIkyf3BjoECR22zpqNfHWtaKmo3aJFpoPMI3h5VabhTaJr9dwGehlyaJZNVDTEV+xYf82S6zpTqAKzEJdkx2YoisWHRDLm0EtTTdiCDgIeGx/CdPK71iEXAf++EyjwKBgBVTIiHmm/Y4VDt31gs1WB9lLV8w+QXtTf2hfB3QpesoJ1USaShR69Exce0AWNTPGEPtZFa2a/tKV244BMpoOWTFyqHGCfWTP3X/L70LlToLhfXBMUGhzRfIQ/XaYYb4nPX71wOtUd49L52rclJO0UxtbuDSnlpCql5tbIP3nAR1AoGAWuAMU3rPsdsFlbm2Pemks00ZPHI4CRllKEhRIljNkCP5v3LTdtyOPum7XoXQF1ayxL77he8SHIRfz3ExXlARl8o+JUi16gv/uMoDT2SwwrphfdX0rCWx0d2anLuVefR8TFcFFkYEVvi5zVezM66sm9YdXozUcbgpo45juQ41L1w=
                certificate: MIICqDCCAZACCQC6LtSYrv20RjANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQKDAtMQUEsIENOPXB1aTAeFw0yMTExMTgxNTA0MjlaFw0zMTExMTgxNTA0MjlaMBYxFDASBgNVBAoMC0xBQSwgQ049cHVpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5VbzisEarCXp2c1XM9JaxpHnbvrfXExqL/ZH0dNJaeRTn0rvDYncE3Qrj5YifpmmmeHF1LF6kGNUcUfNMLbM0zJWvBjJH7afHGG7OaYlHx9pKCfZQ/qSh+Fq0LY97LQTtHuH61ef4Ncpg1kzVSv9FAp7D88nFI6vfhlEV+rjqCf4ItmcwdFkGvWygpZKE4tl7lhoTjEJ2fynbXuDmGzpO5ENLOB9WM+xrViJH5jQRfbItzXKVE2N/WnzXFbvgpbI6ztKIBCUkiD52OHgRHAvNkF+cWCAht+WIeCKSVizbbmkDsbcTYevLTdNaSOsdByGI1u7h5l0PjV80LoL+FEnqwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQB4hye9SIRYUv1WpCBACYxEiCKQSPTOAsvTd7livprExwLUTTx84rAJbO1CvDHjk0N4aWx5ray/UUp15cSPsdSq0wXpHFDsudXYz6YZiE3kP9YlxsfIuTPKbQYF7suU2eNTC1TAsA9WNQsmFaRzwaJd2EaGODnHkshq7wpd34hVAw0aHr4doKv39Z73hBQHQnFwHg4j/9J/lCMOBOpBAIaUBfxPYn31OrvuzOqm2at2aNE+LnlprEHPOg9jwghBZQNkx6tSSbgBPm60ukulYF2/n7HrckpHakojhOyTbN81YvdoH4Xd3te0luOX+nmWEVCK76t0YUQDXG5WTV12/yfi


  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  cloud:
    aws:
      s3:
        endpoint: https://s3.localhost.localstack.cloud:4566
        region: eu-west-2
      credentials:
        access-key: test-access-key
        secret-key: test-secret-key

#logging:
#  level:
#    org.springframework.security.saml: DEBUG
#    org.opensaml: DEBUG
#    org.springframework.web: DEBUG
#  thymeleaf: # Thymeleaf
#    cache: false

logging:
  level:
    uk.gov.laa.ccms.caab: DEBUG
    software:
      amazon:
        awssdk:
          request: DEBUG

os:
  api:
    hostname: localhost
    port: 8051
    url: http://${os.api.hostname}:${os.api.port}
    key: TEST_KEY

av:
  enabled: true
  api:
    hostname: localhost
    port: 3310
    timeout: 20000

laa:
  ccms:
    s3:
      buckets:
        document-bucket:
          name: laa-ccms-documents
          url-duration: 20
    ebs-api:
      hostname: localhost
      port: 8009
      url: http://${laa.ccms.ebs-api.hostname}:${laa.ccms.ebs-api.port}
      access-token: d594f93f-e767-4b88-a9e9-2913441edfba
    soa-api:
      hostname: localhost
      port: 8007
      url: http://${laa.ccms.soa-api.hostname}:${laa.ccms.soa-api.port}
      access-token: 94549740-5aaa-4cd9-b9d9-666159d268a9
    caab-api:
      hostname: localhost
      port: 8005
      url: http://${laa.ccms.caab-api.hostname}:${laa.ccms.caab-api.port}
      access-token: c196393a-f279-45ba-b5d5-f93e6d30465a
    assessment-api:
      hostname: localhost
      port: 8008
      url: http://${laa.ccms.assessment-api.hostname}:${laa.ccms.assessment-api.port}
      access-token: 78bd752c-814c-4fb5-801b-193839c8e768
    oracle-web-determination-server:
      hostname: localhost
      port: 7001
      url: http://${laa.ccms.oracle-web-determination-server.hostname}:${laa.ccms.oracle-web-determination-server.port}/opa/web-determinations
      resources:
        interview-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.css
        font-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/fonts/fonts.css
        interview-javascript: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.js
      redirect:
        hostname: localhost
        port: 8010
        url: http://${laa.ccms.oracle-web-determination-server.redirect.hostname}:${laa.ccms.oracle-web-determination-server.redirect.port}
    caab:
      opa:
        security:
          password: passw0rd

server:
  port: 8010
  servlet:
    session:
      cookie:
        name: CAAB_JSESSIONID
