search:
  max-results:
    page: 20
#    notification-count: 500
#    notifications: 500
    clients: 200
    cases: 100
#    statement-of-accounts: 400
    organisations: 500

submission:
  max-poll-count: 6

notification:
  attachment:
    max-poll-count: 6

spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            assertingparty:
              metadata-uri: ${SAML_METADATA_URI}
            signing:
              credentials:
                private-key: ${SAML_PRIVATE_KEY}
                certificate: ${SAML_CERTIFICATE}

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
      resolve-lazily: true
  cloud:
    aws:
      s3:
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

  # required to be on civil in order for OPA integration with OWD,
  # otherwise issues occur with the JSESSIONID cookie
  servlet:
    context-path: /civil

laa:
  ccms:
    s3:
      buckets:
        document-bucket:
          name: ${S3_DOCUMENT_BUCKET}
          url-duration: 20 # (minutes) - How long generated URLs remain accessible.
    ebs-api:
      hostname: ${CAAB_EBS_API_HOSTNAME}
      url: ${laa.ccms.ebs-api.hostname}
      accessToken: ${CAAB_EBS_API_ACCESS_TOKEN}
    soa-api:
      hostname: ${CAAB_SOA_API_HOSTNAME}
      url: ${laa.ccms.soa-api.hostname}
      accessToken: ${CAAB_SOA_API_ACCESS_TOKEN}
    caab-api:
      hostname: ${CAAB_API_HOSTNAME}
      url: ${laa.ccms.caab-api.hostname}
      accessToken: ${CAAB_API_ACCESS_TOKEN}
    assessment-api:
      hostname: ${ASSESSMENT_API_HOSTNAME}
      url: ${laa.ccms.assessment-api.hostname}
      accessToken: ${ASSESSMENT_API_ACCESS_TOKEN}
    oracle-web-determination-server:
      hostname: ${OWD_URL}
      url: ${laa.ccms.oracle-web-determination-server.hostname}
      resources:
        interview-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.css
        font-styling: ${laa.ccms.oracle-web-determination-server.url}/staticresource/fonts/fonts.css
        interview-javascript: ${laa.ccms.oracle-web-determination-server.url}/staticresource/interviews.js
      redirect:
        hostname: ${OWD_REDIRECT_URL}
        url: ${laa.ccms.oracle-web-determination-server.redirect.hostname}
    caab:
      upload:
        valid-extensions: >
          PDF,
          DOCX,
          RTF,
          TIFF
      opa:
        security:
          password:  ${OPA_SECURITY_PASSWORD}

os:
  api:
    url: ${OS_API_HOSTNAME}
    key: ${OS_API_KEY}

av:
  enabled: ${AV_API_ENABLED}
  api:
    hostname: ${AV_API_HOSTNAME}
    port: ${AV_API_PORT}
    timeout: ${AV_API_TIMEOUT}
