package uk.gov.laa.ccms.caab.config;

import lombok.Getter;

/**
 * Enumerates the allowed user roles.
 */
@Getter
public enum UserRole {

  AMEND_CASE("AC"),
  ADD_PROCEEDING("ADDPROC"),
  VIEW_NOTIFICATION_ATTACHMENT("ATT"),
  CREATE_BILL("BILL"),
  CREATE_APPLICATION("CA"),
  VIEW_CASE_BILL("CB"),
  VIEW_CLIENT_DETAILS("CD"),
  CLEAR_OUTCOME("CLROUT"),
  DELETE_BILL("DB"),
  DELETE_PROCEEDING("DELPROC"),
  UPLOAD_EVIDENCE("EVID"),
  VIEW_NOTIFICATIONS("NOT"),
  CREATE_PAYMENT_ON_ACCOUNT("POA"),
  REQUEST_CASE_DISCHARGE("POD"),
  CREATE_CASE_REQUEST("PRC"),
  CREATE_PROVIDER_REQUEST("PRNC"),
  SUBMIT_AMENDMENT("SUBAMD"),
  SUBMIT_APPLICATION("SUBAPP"),
  SUBMIT_BILL("SUBBILL"),
  SUBMIT_DOCUMENT_UPLOAD("SUBDOC"),
  SUBMIT_NOTIFICATION("SUBNOT"),
  SUBMIT_REGISTER_CLIENT("SUBRC"),
  SUBMIT_CASE_OUTCOME("SUBOUT"),
  SUBMIT_PAYMENT_ON_ACCOUNT("SUBPOA"),
  SUBMIT_UPDATE_CLIENT("SUBUC"),
  ENTER_UNDERTAKING("UND"),
  UPDATE_PROCEEDING_OUTCOME("UPDOUT"),
  UPDATE_PROCEEDING("UPDPROC"),
  VIEW_CASE_DETAILS("VC"),
  VIEW_PROCEEDING_OUTCOME("VIEWOUT"),
  VIEW_PROCEEDING("VIEWPROC"),
  VIEW_OUTCOME("VO"),
  VIEW_CASES_AND_APPLICATIONS("YCA"),
  ALLOW_FAST_FORWARD("FFBUT");

  private final String code;

  /**
   * Initializes the enum with the specified code.
   *
   * @param code the PUI code for this role.
   */
  UserRole(final String code) {
    this.code = code;
  }
}
