# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Civil Applications And Billing Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  packages: write

jobs:
  define-image-tag:
    runs-on: ubuntu-latest
    # map a step output to job output
    outputs:
      tag_name: ${{ steps.extract_tag_name.outputs.tag_name }}
    steps:
      - name: Extract short repo name
        shell: bash
        run: echo "repo_name=${GITHUB_REPOSITORY#*\/laa-ccms-}-ui" >> $GITHUB_OUTPUT
        id: extract_repo_name
      - name: derive tag name
        shell: bash
        run: echo "tag_name=${{ steps.extract_repo_name.outputs.repo_name }}-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        id: extract_tag_name


  build-test:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variables
        env:
          GIT_PACKAGE_KEY: ${{ secrets.GIT_PACKAGE_KEY }}
        run: echo "GIT_PACKAGE_KEY=${GIT_PACKAGE_KEY}" >> $GITHUB_ENV

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - name: upload jarfile
        uses: actions/upload-artifact@v3
        with:
          name: caab-jar
          path: build/libs/laa-ccms-caab-0.0.1-SNAPSHOT.jar

      - name: Test
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: jacocoTestCoverageVerification

      - name: Integration Test
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: integrationTest

  delete-artifact:
    needs: [ build-test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: caab-jar
